# Informations du site
title: "Yan AKOUEDENOUDJE"
description: "Portfolio d'un futur ingénieur R&D en Mécatronique et Agroéquipements"
logo: "/assets/images/profile.png"

# URL GitHub Pages
url: "https://yanakouedenoudje.github.io"
baseurl: ""

# Thème GitHub Pages
theme: jekyll-theme-minimal

# Langue
lang: fr-FR

# Auteur
author:
  name: "Yan AKOUEDENOUDJE"
  email: ""

# Réglages Markdown
markdown: kramdown

# Plugins compatibles GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Affichage
show_downloads: true

# Navigation
nav:
  - title: "Accueil"
    url: "/"

  - title: "Projets"
    url: "/projects"

  - title: "Compétences"
    url: "/skills"

  - title: "CV"
    url: "/cv"

  - title: "Contact"
    url: "/contact"

# Collections
collections:
  projects:
    output: true

# Exclure certains fichiers
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
